selector:
  enable_static: False
  enable_dunamic: False
  N_clusters: 4
  K_keywords: 10

aggregator:
  extractor_model: ""
  generalizer_model: ""
  K_topics: 4

reducer:
  model: ""

retriever:
  model_path: '/home/aisummer/mikhail_workspace/nlp-service/models/intfloat/multilingual-e5-small'
  
  densedb_path: '/home/aisummer/mikhail_workspace/nlp-service/data/infsec_gosts/dbs/v2/densedb'
  sparsedb_path: '/home/aisummer/mikhail_workspace/nlp-service/data/infsec_gosts/dbs/v2/sparsedb'
  densedb_kwargs: {'allow_dangerous_deserialization': True}
  sparsedb_kwargs: {}

  model_kwargs: {'device':'cuda'}
  encode_kwargs: {'normalize_embeddings': True, 'prompt': 'query: '}
  
  params: {'similarity': {'k': 3}, 'bm25': {'k': 3}}
  weights: [0.5, 0.5]

summarizer:
  model: ""

generator:
  model: ""

controller:
  enable_static: False
  enable_dynamic: False
  
  