selector:
  enable_static: False
  enable_dunamic: False
  N_clusters: 4
  K_keywords: 10

aggregator:
  extractor_model: ""
  generalizer_model: ""
  K_topics: 4

reducer:
  model: ""

retriever:
  mode: 'threshold'
  custom_args: 
    model_path: '/nlp_service/models/intfloat/multilingual-e5-small'
    densedb_path: '/nlp_service/data/infsec_gosts/dbs/v2/densedb'
    densedb_kwargs: {'allow_dangerous_deserialization': True}
    model_kwargs: {'device':'cuda'}
    encode_kwargs: {'normalize_embeddings': True, 'prompt': 'query: '}
    params: {"threshold": 0.80, "fetch_k": 30, "max_k": 10}
  
summarizer:
  tech_config:
    model_path: '/nlp_service/models/model_llm/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa'
    n_gpu_layers: -1
    seed: 42
    n_ctx: 0
    n_batch: 512
    n_threads: null
    use_mmap: True
    use_mlock: True
    assistant_prompt: "Твоя база знаний, все ответы генерируются на основе текста ниже:"
    system_prompt: "Ты вопросно-ответная система. Все ответы генерируешь на русском языке. Отвечай коротко по вопросам."
    stub_answer: "К сожалению, в моей базе документов по информационной безопасности отсутствует релевантная информация по вашему вопросу.\ 
    Попробуйте переформулировать/уточнить ваш вопрос или выполните ручной поиск по [базе документов](https://www.gost.ru/portal/gost/home/standarts/InformationSecurity)."

  strat_config:
    temperature: 0.6
    top_k: 40
    top_p: 0.9
    min_p: 0.05
    typical_p: 1
    stream: True
    max_tokens: 90

generator:
  model: ""

controller:
  enable_static: False
  enable_dynamic: False