selector:
  enable_static: False
  enable_dunamic: False
  N_clusters: 4
  K_keywords: 10

aggregator:
  extractor_model: ""
  generalizer_model: ""
  K_topics: 4

reducer:
  model: ""

retriever:
  model_path: '/home/aisummer/mikhail_workspace/nlp-service/models/intfloat/multilingual-e5-small'
  model_kwargs: {'device':'cuda'}
  encode_kwargs: {'normalize_embeddings': False, 'prompt': 'query: '}
  faiss_kwargs: {'distance_strategy': 'EUCLIDEAN_DISTANCE'}
  vectordb_path: ""
  base_search_type: "similarity_score_threshold"
  base_search_config: {"score_threshold": 0.5}

summarizer:
  model: ""

generator:
  model: ""

controller:
  enable_static: False
  enable_dynamic: False
  
  