selector:
  enable_static: False
  enable_dunamic: False
  N_clusters: 4
  K_keywords: 10

aggregator:
  extractor_model: ""
  generalizer_model: ""
  K_topics: 4

reducer:
  model: ""

retriever:
  model_path: '/nlp_service/models/intfloat/multilingual-e5-small'
  densedb_path: '/nlp_service/data/infsec_gosts/dbs/v2/densedb'
  sparsedb_path: '/nlp_service/data/infsec_gosts/dbs/v2/sparsedb'
  densedb_kwargs: {'allow_dangerous_deserialization': True}
  sparsedb_kwargs: {}
  model_kwargs: {'device':'cuda'}
  encode_kwargs: {'normalize_embeddings': True, 'prompt': 'query: '}
  params: {'similarity': {'k': 3}, 'bm25': {'k': 3}}
  weights: [0.5, 0.5]

summarizer:
  assist_prompt: "Твоя база знаний, все ответы генерируются на основе текста ниже:"
  system_prompt: "Ты вопросно-ответная система. Все ответы генерируешь на русском языке. Отвечай коротко по вопросам."
  num_ctx: 1024
  num_keep: 5 
  seed: 42
  num_predict: 100
  tfs_z: 0.5
  temperature: 0.8
  mirostat_tau: 0.8
  mirostat_eta: 0.6
  top_k: 20
  top_p: 0.9 
  typical_p: 0.7
  repeat_last_n: 33
  mirostat: 1
  repeat_penalty: 1.2
  presence_penalty: 1.5
  frequency_penalty: 1.0
  penalize_newline: True

generator:
  model: ""

controller:
  enable_static: False
  enable_dynamic: False
  
  