selector:
  enable_static: False
  enable_dunamic: False
  N_clusters: 4
  K_keywords: 10

aggregator:
  extractor_model: ""
  generalizer_model: ""
  K_topics: 4

reducer:
  model: ""

retriever:
  model_path: '/home/aisummer/nlp_models/intfloat/multilingual-e5-small'
  densedb_path: '/home/aisummer/mikhail_workspace/nlp_service/data/infsec_gosts/dbs/v2/densedb'
  sparsedb_path: '/home/aisummer/mikhail_workspace/nlp_service/data/infsec_gosts/dbs/v2/sparsedb'
  densedb_kwargs: {'allow_dangerous_deserialization': True}
  sparsedb_kwargs: {}
  model_kwargs: {'device':'cuda'}
  encode_kwargs: {'normalize_embeddings': True, 'prompt': 'query: '}
  params: {'similarity': {'k': 3}, 'bm25': {'k': 3}}
  weights: [0.5, 0.5]

summarizer:
  tech_config:
    model_path: '/home/aisummer/nlp_models/model_llm/blobs/sha256-6a0746a1ec1aef3e7ec53868f220ff6e389f6f8ef87a01d77c96807de94ca2aa'
    n_gpu_layers: -1
    seed: 42
    n_ctx: 512
    n_batch: 512
    n_threads: null
    use_mmap: True
    use_mlock: True
    assistant_prompt: "Твоя база знаний, все ответы генерируются на основе текста ниже:"
    system_prompt: "Ты вопросно-ответная система. Все ответы генерируешь на русском языке. Отвечай коротко по вопросам."

  strat_config:
    temperature: 0.8
    top_k: 40
    top_p: 0.95
    min_p: 0.05 
    typical_p: 1 
    stream: True
    max_tokens: 100

    


generator:
  model: ""

controller:
  enable_static: False
  enable_dynamic: False
  
  